include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/test_signup.dart
    - lib/core/services/firebase_test.dart
  errors:
    deprecated_member_use: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore