// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbftCgOaJNENau0DG3kv2woH3V1mett0k',
    appId: '1:359666384524:web:bed7c3533cb9fed94105a9',
    messagingSenderId: '359666384524',
    projectId: 'kodekid-c59ef',
    authDomain: 'kodekid-c59ef.firebaseapp.com',
    storageBucket: 'kodekid-c59ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbftCgOaJNENau0DG3kv2woH3V1mett0k',
    appId: '1:359666384524:android:bed7c3533cb9fed94105a9',
    messagingSenderId: '359666384524',
    projectId: 'kodekid-c59ef',
    storageBucket: 'kodekid-c59ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQgjK_8jGr48FVe-Vv1lj7RDw4iFcplVg',
    appId: '1:359666384524:ios:a32b7be0c8bdc47c4105a9',
    messagingSenderId: '359666384524',
    projectId: 'kodekid-c59ef',
    storageBucket: 'kodekid-c59ef.firebasestorage.app',
    iosBundleId: 'com.example.kodekid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQgjK_8jGr48FVe-Vv1lj7RDw4iFcplVg',
    appId: '1:359666384524:ios:a32b7be0c8bdc47c4105a9',
    messagingSenderId: '359666384524',
    projectId: 'kodekid-c59ef',
    storageBucket: 'kodekid-c59ef.firebasestorage.app',
    iosBundleId: 'com.example.kodekid',
  );
}